In [2]:
import numpy as np

**Array Operations**

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
sum = a1 + a2
sum

array([ 7,  9, 11, 13, 15])

In [4]:
sub = a2 - a1
sub

array([5, 5, 5, 5, 5])

In [5]:
multiply = a1 * a2
multiply

array([ 6, 14, 24, 36, 50])

In [11]:
divide = a1 / a2
divide

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
mod = a2 % a1
mod

array([0, 1, 2, 1, 0])

In [12]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [13]:
arr = np.array([1,2,3,4,5])
arr + 10

array([11, 12, 13, 14, 15])

**Broadcasting**

In [18]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
arr2 = np.arange(1,21).reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [21]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [22]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
slice = arr[:5]
slice = slice + 10
slice

array([11, 12, 13, 14, 15])

In [40]:
arr  # Original do not change

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
b = a
b       # Deep Copy of a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
c = a.copy() 
c                 #Shallow copy

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
c[0] = 33
c

array([33,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Matrix Operations**

In [65]:
mat1 = np.array([[1,2], [3,4]])
mat2 = np.array([[5,6], [7,8]])

In [66]:
mat1

array([[1, 2],
       [3, 4]])

In [67]:
mat2

array([[5, 6],
       [7, 8]])

In [59]:
# Multiply

In [60]:
mat1 @ mat2

array([[19, 22],
       [43, 50]])

In [61]:
np.dot(mat1, mat2)

array([[19, 22],
       [43, 50]])

In [62]:
mat1.T

array([[1, 3],
       [2, 4]])

In [63]:
mat2.T

array([[5, 7],
       [6, 8]])

**Advance Operations**

**Stacking Array**

In [69]:
A = np.array([1,2,3,4,5])
B = np.array([6,7,8,9,10])
np.vstack((A, B))   # Vertical stack

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [74]:
np.hstack((A, B))   # Horizontal Stack

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
np.column_stack((A, B))     # 2D column stack

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

**Splitting Array**

In [7]:
c = np.arange(1, 17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
np.hsplit(c, 4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [13]:
np.hsplit(c, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [11]:
np.vsplit(c, 4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [12]:
np.vsplit(c, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]