**Imports**

In [30]:
import numpy as np
import random

**Numpy Array**

In [29]:
arr = np.array([1,2,3,4,5])   #  Numpy Array
arr

array([1, 2, 3, 4, 5])

In [28]:
arr = np.linspace(1,10,20)     # linear Space
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [25]:
random_arr = np.random.rand(5)
random_arr

array([0.61155743, 0.61496617, 0.1390683 , 0.94103644, 0.93814577])

In [29]:
random_arr = np.random.randint(1, 10, 10)
random_arr

array([3, 3, 7, 4, 1, 1, 2, 4, 1, 3], dtype=int32)

In [24]:
arr = np.array([[1,2,3],[4,5,6]])  # 2D array
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[11,12,13],[14,15,16],[17,18,19]],
                [[21,22,23],[24,25,26],[27,28,29]]])
arr              # 3D array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [23]:
arr.shape   # Shape

(6, 5)

In [22]:
new_arr = np.arange(1,11)  # Range
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
new_arr.dtype # Data Type

dtype('int64')

**Numpy Indexing And Slicing**

In [19]:
new_arr[5]  # Index

np.int64(6)

In [10]:
array = arr[1:9]     # Slicing
array

array([2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr = np.arange(1, 31).reshape(6, 5)  # Reshape and Resize
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [41]:
arr[3:, 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [42]:
arr[:, 2]

array([ 3,  8, 13, 18, 23, 28])

**Boolean**

In [44]:
bool_index = np.arange(11,21)
bool_index

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
evens = bool_index %2 == 0
evens

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [50]:
arr = bool_index[evens]
arr

array([12, 14, 16, 18, 20])

**Methods**